/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hemsire;

import database.DBConnection;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merve
 */
public class hastaAraPaneli extends javax.swing.JPanel {

    /**
     * Creates new form hastaAraPaneli
     */
    public anasayfaPaneli anasayfa;
    public ajandaPaneli ajanda;
    public hastaAraPaneli hastaAra;
    public shiftYonetimiPaneli shiftYonetimi;
    public kullaniciAyarlar kullaniciAyar;
    public Giris girisSayfasi;
    DBConnection d;
    DefaultTableModel dtmTumHastalar, dtmSorgu;
    Ekran e;
    
     private DefaultListModel dlm;

    public hastaAraPaneli(Ekran ekran) {
        initComponents();
        e=ekran;
        this.setSize(950, 450);
        d = new DBConnection();
        ResetTumHastalarTablosuDtm();
        sorguTablosuDtm();
        d.ayrintiliHastaBilgisi(dtmTumHastalar);
       resetList();
        d.hastaListesi(dlm, Ekran.kullaniciAd);
    }

    void ResetTumHastalarTablosuDtm() {
        dtmTumHastalar = new DefaultTableModel();
        dtmTumHastalar.setColumnIdentifiers(new String[]{"TC No", "Hasta Adı", "Hasta Soyadı", "Doktor Adı"});
        tumHastalarTablosu.setModel(dtmTumHastalar);

    }
    
    public void resetList() {
        dlm = new DefaultListModel();
        jList1.setModel(dlm);
        jList1.setVisible(true);

    }

    void sorguTablosuDtm() {
        dtmSorgu = new DefaultTableModel();
        dtmSorgu.setColumnIdentifiers(new String[]{"TC No", "Hasta Adı", "Hasta Soyadı", "Doktor Adı"});
        sorguSonuclarTablosu.setModel(dtmSorgu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hastaAraPaneli = new javax.swing.JPanel();
        TabbedPanes = new javax.swing.JTabbedPane();
        sorguSonuclari = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sorguSonuclarTablosu = new javax.swing.JTable();
        tumHastalar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tumHastalarTablosu = new javax.swing.JTable();
        calisilanlar = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        hastaAramaPaneli = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        hastaNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        hastaAraPaneli.setBackground(new java.awt.Color(255, 255, 255));
        hastaAraPaneli.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)), "Hasta Konsolu"));
        hastaAraPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sorguSonuclarTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(sorguSonuclarTablosu);

        javax.swing.GroupLayout sorguSonuclariLayout = new javax.swing.GroupLayout(sorguSonuclari);
        sorguSonuclari.setLayout(sorguSonuclariLayout);
        sorguSonuclariLayout.setHorizontalGroup(
            sorguSonuclariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorguSonuclariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        sorguSonuclariLayout.setVerticalGroup(
            sorguSonuclariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sorguSonuclariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPanes.addTab("Sorgu Sonuçları", sorguSonuclari);

        tumHastalar.setPreferredSize(new java.awt.Dimension(250, 234));

        tumHastalarTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tumHastalarTablosu);

        javax.swing.GroupLayout tumHastalarLayout = new javax.swing.GroupLayout(tumHastalar);
        tumHastalar.setLayout(tumHastalarLayout);
        tumHastalarLayout.setHorizontalGroup(
            tumHastalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumHastalarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        tumHastalarLayout.setVerticalGroup(
            tumHastalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumHastalarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPanes.addTab("Tüm Hastalar", tumHastalar);

        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout calisilanlarLayout = new javax.swing.GroupLayout(calisilanlar);
        calisilanlar.setLayout(calisilanlarLayout);
        calisilanlarLayout.setHorizontalGroup(
            calisilanlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calisilanlarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        calisilanlarLayout.setVerticalGroup(
            calisilanlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calisilanlarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPanes.addTab("Çalışılanlar", calisilanlar);

        hastaAraPaneli.add(TabbedPanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 910, 290));

        hastaAramaPaneli.setBackground(new java.awt.Color(153, 153, 255));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hasta Arama");

        jLabel14.setText("TC No");

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sorgula");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hastaAramaPaneliLayout = new javax.swing.GroupLayout(hastaAramaPaneli);
        hastaAramaPaneli.setLayout(hastaAramaPaneliLayout);
        hastaAramaPaneliLayout.setHorizontalGroup(
            hastaAramaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hastaAramaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hastaAramaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(hastaNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        hastaAramaPaneliLayout.setVerticalGroup(
            hastaAramaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hastaAramaPaneliLayout.createSequentialGroup()
                .addGroup(hastaAramaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hastaAramaPaneliLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14))
                    .addGroup(hastaAramaPaneliLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(hastaAramaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(hastaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hastaAraPaneli.add(hastaAramaPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(hastaAraPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hastaAraPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sorguTablosuDtm();

        d.sorgula(dtmSorgu,hastaNo.getText());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPanes;
    private javax.swing.JPanel calisilanlar;
    private javax.swing.JPanel hastaAraPaneli;
    private javax.swing.JPanel hastaAramaPaneli;
    private javax.swing.JTextField hastaNo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable sorguSonuclarTablosu;
    private javax.swing.JPanel sorguSonuclari;
    private javax.swing.JPanel tumHastalar;
    private javax.swing.JTable tumHastalarTablosu;
    // End of variables declaration//GEN-END:variables
}
